query home_page {
  homePage(where: {
    id: "cjj6i30tffkiq09140r1w4uy8"
  }) {
    id
    title
    subtitle
    bannerImage {
      fileName
      url
    }
    section1Image {
      fileName
      url
    }
    section1Header
    section1Subheader
    section1Text
    sectionHeader
    sectionSubheader
    sectionImage {
      fileName
      url
    }
  }
}
  